### PR TITLE
Update casino gem dependency to allow v3 and v4

### PR DESCRIPTION
**Pull request by adamcrown**
Tried this out with CASino 4.0.2. Worked fine.

### CODE REVIEW

**Comment by bonyiii** [comment]
Hi, thanks for the pr, but the travis build for: 1.9.3 ruby has failed, i will check it.

**Comment by adamcrown** [comment]
I'm seeing the same error in some of my other gems but only for certain Ruby versions. If I figure out what's going on I'll be sure to let you know.

**Comment by adamcrown** [comment]
Looks like that fixed it.

**Comment by bonyiii** [comment]
@plukacs
Thanks! I find someone who has write permission and we are going to merge.

**Pull request merged**
